-- Run in a fresh Supabase project's SQL Editor. Replace ADMIN_EMAIL_HERE first.
create table if not exists public.cases (
  id bigint generated by default as identity primary key,
  slug text unique not null check (slug ~ '^case-[0-9]{3}$'),
  case_number text unique not null,
  title text not null,
  short_description text not null,
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.site_settings (
  id smallint primary key default 1 check (id = 1),
  active_case_id bigint not null references public.cases(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

insert into public.cases(slug,case_number,title,short_description) values
('case-001','001','Xin nhỏ em hết giận','Hồ sơ xin lỗi màu hồng dễ thương nguyên bản.'),
('case-002','002','Xin lỗi em Ý vì quên gọi lúc 8 giờ','Biên bản sự cố báo thức, cuộc gọi và gác đàn.')
on conflict(slug) do update set title=excluded.title,short_description=excluded.short_description;
insert into public.site_settings(id,active_case_id) select 1,id from public.cases where slug='case-001' on conflict(id) do nothing;

alter table public.cases enable row level security;
alter table public.site_settings enable row level security;

-- JWT email is verified by Supabase Auth. This is the sole admin allow-list.
create or replace function public.is_site_admin() returns boolean language sql stable security definer set search_path='' as $$
  select coalesce((select auth.jwt()->>'email') = 'ADMIN_EMAIL_HERE', false)
$$;
revoke all on function public.is_site_admin() from public;
grant execute on function public.is_site_admin() to anon, authenticated;

-- Anonymous visitors may see only the enabled case selected in the singleton setting.
create policy "public reads active case" on public.cases for select to anon using (
  is_enabled and id = (select active_case_id from public.site_settings where id=1)
);
-- The active id itself is public; it reveals no admin identity or credentials.
create policy "public reads active setting" on public.site_settings for select to anon using (id=1);
create policy "admin reads all cases" on public.cases for select to authenticated using (public.is_site_admin());
create policy "admin reads setting" on public.site_settings for select to authenticated using (public.is_site_admin());
-- Only the allow-listed authenticated admin can switch to an existing enabled case.
create policy "admin updates active setting" on public.site_settings for update to authenticated
using (public.is_site_admin()) with check (public.is_site_admin() and exists(select 1 from public.cases where id=active_case_id and is_enabled));

grant select on public.cases,public.site_settings to anon,authenticated;
grant update(active_case_id) on public.site_settings to authenticated;
revoke insert,update,delete on public.cases from anon,authenticated;
revoke insert,delete on public.site_settings from anon,authenticated;

create or replace function public.stamp_site_settings() returns trigger language plpgsql security invoker as $$ begin new.updated_at=now();new.updated_by=auth.uid();return new;end $$;
create trigger site_settings_audit before update on public.site_settings for each row execute function public.stamp_site_settings();
